using System;
using System.Collections.Generic;
using System.IO;

namespace QjySDK.Stg
{
    /// <summary>
    /// 从 poly_secrets.txt 读取 Polymarket 密钥配置
    /// 文件格式: KEY=VALUE（每行一个）
    /// </summary>
    public static class PolySecrets
    {
        private static readonly Lazy<Dictionary<string, string>> _secrets = new(() => Load());

        public static string PrivateKey => Get("PRIVATE_KEY");
        public static string FunderAddress => Get("FUNDER_ADDRESS");
        public static string RelayerApiKey => Get("RELAYER_API_KEY");

        // Cached L2 (CLOB) API credentials. If present, PolymarketService.Init uses these directly
        // instead of calling GetOrCreateApiCredentialsAsync (which fails when a key already exists for the EOA).
        public static string PolyApiKey => Get("POLY_API_KEY");
        public static string PolyApiSecret => Get("POLY_API_SECRET");
        public static string PolyApiPassphrase => Get("POLY_API_PASSPHRASE");

        /// <summary>
        /// Polymarket "Developer Code" — a separate ECDSA private key generated by Polymarket and shown
        /// on the developer page. Its public address is the canonical "API KEY signer address" that the
        /// CLOB server compares order.signer against for POLY_1271 (deposit wallet) accounts.
        /// </summary>
        public static string PolyDevCode => Get("POLY_DEV_CODE");

        // --- Builder API key for the Polymarket Relayer (https://relayer-v2.polymarket.com) ---
        // Auth headers are POLY_BUILDER_API_KEY / POLY_BUILDER_PASSPHRASE / POLY_BUILDER_TIMESTAMP / POLY_BUILDER_SIGNATURE,
        // computed via the same HMAC-SHA256(secret_b64url) over (timestamp || method || path || body) scheme as L2.
        // Used by the relayer to sponsor gasless transactions: deposit-wallet deployment, token approvals,
        // CTF split/merge/redeem, and signed wallet-batch execution.
        public static string PolyBuilderApiKey => Get("POLY_BUILDER_API_KEY");
        public static string PolyBuilderApiSecret => Get("POLY_BUILDER_API_SECRET");
        public static string PolyBuilderApiPassphrase => Get("POLY_BUILDER_API_PASSPHRASE");

        public static string Get(string key)
        {
            _secrets.Value.TryGetValue(key, out var val);
            return val ?? string.Empty;
        }

        private static Dictionary<string, string> Load()
        {
            var dic = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            var candidates = new[]
            {
                Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", "poly_secrets.txt"),
                Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "poly_secrets.txt"),
                Path.Combine(AppContext.BaseDirectory, "poly_secrets.txt"),
                Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), "poly_secrets.txt"),
            };

            foreach (var p in candidates)
            {
                var full = Path.GetFullPath(p);
                if (!File.Exists(full)) continue;

                foreach (var line in File.ReadAllLines(full))
                {
                    var trimmed = line.Trim();
                    if (string.IsNullOrEmpty(trimmed) || trimmed.StartsWith("#")) continue;
                    var idx = trimmed.IndexOf('=');
                    if (idx > 0)
                        dic[trimmed[..idx].Trim()] = trimmed[(idx + 1)..].Trim();
                }
                break;
            }

            return dic;
        }
    }
}
